### ISSUE TITLE
Error with hapi ^9.1.0

### ISSUE THREAD

**Issue by Martindelataille** [nesive/hapi-json-view#25]
When run sudo npm install --save hapi-json-view, I got this error:

error peerinvalid The package hapi does not satisfy its siblings' peerDependencies requirements!
error peerinvalid Peer hapi-json-view@3.0.0 wants hapi@9.x.x.

Can you publish to npm the new version ?

Thanks.

**Comment by gergoerdosi** [comment]
Released the new version (4.0.0) which supports hapi 10 and 11. Please note that this is a new major version with breaking changes:

- It now requires node v4 or newer.
- Package has been renamed to `@nesive/hapi-json-view`.
- Compilation mode became synchronous (remove `compileMode: 'async'` from your config).

**Comment by Martindelataille** [comment]
Nice work ! Thanks
