### ISSUE TITLE
ES6 issue

### ISSUE THREAD

**Issue by Martindelataille** [nesive/hapi-json-view#29]
The ES6 change break all my app.

Do we need to change our template with ES6 too ?

**Comment by gergoerdosi** [comment]
Can you please give me more information? The next major version (4.0.0) will require node v4 or newer. Do you have issues when running on node v4 or v5 too?

**Comment by Martindelataille** [comment]
I tried with v4.1.0 and v5.0.0

I tried to see whats happen and error seems to be that "renderer" is never call in compile function.

```
function renderer(context) {
   console.log('renderer',  context)
    return JSON.stringify(runtime.run(template, context));
}
return renderer;
```

**Comment by gergoerdosi** [comment]
There was a breaking change, I made compilation synchronous. Can you try to remove `compileMode: 'async',` from your config, or just set it to `sync` (`sync` is the default)?

**Comment by Martindelataille** [comment]
Yes, i remove it and it work :)

Thanks

**Comment by gergoerdosi** [comment]
Ok, I'm going to release the new version then.
